<a href="https://colab.research.google.com/github/LeslyVictoria2/CSST-104---ADVANCED-MACHINE-LEARNING/blob/main/3B_VICTORIA_LAB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CSST 104 - ADVANCED MACHINE LEARNING**

**LESLY-ANN B. VICTORIA from BSCS-IS-3B - LABORATORY 4**

**1. Importing Libraries:**

In [ ]:
import pandas as pd #Data Manupilation
import numpy as np #Mathematical or Numerical Operation
import matplotlib.pyplot as plt #Data Visualization
from sklearn.model_selection import train_test_split #Selection
from sklearn.linear_model import LinearRegression #Training Data Modeling
from sklearn.metrics import mean_squared_error

**2. Creating a Synthetic Dataset:**

In [ ]:
np.random.seed() #For Reproducibility
x = np.random.rand(100,3) #
y = x[:,0] * 150000 + x[:,1] * 100000 + x[:,2] * 50000 + 50000

**3. Converting to a DataFrame:**

In [ ]:
data = pd.DataFrame(x, columns=['Size','Bedroom','Age'])
data['Price'] = y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
data.head()

Size   Bedroom       Age          Price
0  0.932422  0.364026  0.726377  262584.770828
1  0.476441  0.276151  0.176346  157898.617903
2  0.333550  0.499374  0.604531  180196.356304
3  0.735073  0.818039  0.203100  252219.781638
4  0.975633  0.918062  0.484535  312377.867777

**4. Initializing the Model:**

In [ ]:
model = LinearRegression()

**5. Fitting the Model:**

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

**6. Making Prediction:**

In [ ]:
predicted_y = model.predict(x_test)
print(x_test)
print(predicted_y)

[[0.0371241  0.86009058 0.41319878]
 [0.39377081 0.37677431 0.28098263]
 [0.56373972 0.74066972 0.87387885]
 [0.36953596 0.77778227 0.0678619 ]
 [0.22623455 0.56180081 0.49537505]
 [0.10608549 0.72929526 0.89665362]
 [0.13998192 0.21209263 0.59464824]
 [0.49115057 0.23465816 0.67226108]
 [0.31847341 0.57922511 0.33184312]
 [0.93242187 0.36402619 0.72637744]
 [0.90177947 0.21692797 0.31308609]
 [0.44119765 0.42052433 0.6610012 ]
 [0.67335952 0.4643875  0.35632225]
 [0.14016446 0.90249259 0.63372619]
 [0.25922065 0.15009499 0.53721224]
 [0.9756329  0.91806178 0.48453511]
 [0.52570171 0.84582983 0.09893097]
 [0.97944734 0.58068056 0.01809332]
 [0.55773739 0.9030318  0.22919023]
 [0.39871013 0.42466515 0.40611   ]]
[162237.61086969 160792.18376562 252321.87282001 186601.71524019
 164884.01500539 183675.02936179 121938.96239927 180751.45478754
 172285.67904836 262584.77082772 222614.02110472 191282.13989796
 215258.78992541 192960.23708257 130753.20814058 312377.86777655
 218384.78864612 25

**7 . Calculating the Mean Squared Erro:**

In [ ]:
mse = mean_squared_error(y_test, predicted_y)
print(f'Mean Squared Error',mse)

Mean Squared Error 3.0493186101154813e-21


**8. Predicting the Price of a New House:**

In [ ]:
new_house = [[0.5,2,10]]
predicted_price = model.predict(new_house)
print('Priceted Price:  ', (predicted_price[0]))

Priceted Price:   825000.0000000002
